### PR TITLE
fix pdf paths

### PR DESCRIPTION
**Pull request by IamShubhamGupto**
- updated `url_pdf` for existing publications

⚠️ Changes may not appear immediately due to cache, test deployment on private / incognito window

### CODE REVIEW

**Comment by IamShubhamGupto** [comment]
Verified the paths have been updated using incognito browser, deleting branch

**Comment by LaureZanna** [comment]
thanks @IamShubhamGupto . we just need to take care of the bottom links on the pages as well and remove them.

**Comment by IamShubhamGupto** [comment]
Hey @LaureZanna, could you tell me more about the bottom links? maybe a screenshot can help clarify

**Comment by LaureZanna** [comment]
@IamShubhamGupto : screenshot is on Slack. Thanks!

**Pull request merged**
